### ISSUE TITLE
Undefined reference

### ISSUE THREAD

**Issue by LukaJankovic** [Richard-W/curl-vala#4]
Not sure if this project is still being maintained, but if anyone is able to point me in the right direction, I'd appreciate it. Here's the error I'm getting when trying to compile vala with libcurl (even when running make in the examples folder)

```
fetch-website.vala.c:(.text+0xfb): undefined reference to `vcurl_easy_new'                                                                    
fetch-website.vala.c:(.text+0x164): undefined reference to `vcurl_easy_set_url'                                                               
fetch-website.vala.c:(.text+0x191): undefined reference to `vcurl_easy_set_followlocation'                                                    
fetch-website.vala.c:(.text+0x1af): undefined reference to `vcurl_easy_perform'                                                               
fetch-website.vala.c:(.text+0x1d4): undefined reference to `vcurl_curl_error_quark' 
```

**Comment by richard-w** [comment]
The fetch-website example works fine for me.
```bash
mkdir build && cd build
../configure
make
sudo make install
cd ../examples
make
LD_LIBRARY_PATH=/usr/local/lib ./fetch-website www.google.de
```
Does your build work with these commands?

**Comment by LukaJankovic** [comment]
Nope... same error. Here's my full log:
```
LThinkpad │ $ mkdir build                                                                                                                                                                                                                                                            │ 1019
LThinkpad │ $ cd build                                                                                                                                                                                                                                                               │ 1020
LThinkpad │ $ ../configure                                                                                                                                                                                                                                                           │ 1021
Found cmake at /usr/bin/cmake
-- The C compiler identification is GNU 7.2.1
-- The CXX compiler identification is GNU 7.2.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Vala: /usr/bin/valac (found version "0.38.4") 
-- Found PkgConfig: /usr/bin/pkg-config (found version "1.3.12") 
-- Found CURL: -lcurl  
-- Checking for module 'glib-2.0'
--   Found glib-2.0, version 2.54.3
-- Checking for module 'gobject-2.0'
--   Found gobject-2.0, version 2.54.3
-- Checking for module 'gio-2.0'
--   Found gio-2.0, version 2.54.3
-- Configuring done
-- Generating done
-- Build files have been written to: /home/Luka/Temp/curl-vala/build
Created config.status
LThinkpad │ $ make                                                                                                                                                                                                                                                                   │ 1022
[ 11%] Generating src/curl-easy.c, src/curl-curlerror.c, src/curl-write-function.c, src/curl-read-function.c, src/curl-functions.c, src/curl-input-stream.c, src/curl-output-stream.c, curl-vala.vapi, curl-vala.h, curl-vala_internal.h
Scanning dependencies of target curl-vala
[ 22%] Building C object CMakeFiles/curl-vala.dir/src/curl-easy.c.o
[ 33%] Building C object CMakeFiles/curl-vala.dir/src/curl-curlerror.c.o
[ 44%] Building C object CMakeFiles/curl-vala.dir/src/curl-write-function.c.o
[ 55%] Building C object CMakeFiles/curl-vala.dir/src/curl-read-function.c.o
[ 66%] Building C object CMakeFiles/curl-vala.dir/src/curl-functions.c.o
[ 77%] Building C object CMakeFiles/curl-vala.dir/src/curl-input-stream.c.o
[ 88%] Building C object CMakeFiles/curl-vala.dir/src/curl-output-stream.c.o
/home/Luka/Temp/curl-vala/src/curl-output-stream.vala: In function ‘vcurl_curl_output_stream_class_init’:
/home/Luka/Temp/curl-vala/src/curl-output-stream.vala:22:43: warning: assignment from incompatible pointer type [-Wincompatible-pointer-types]
  public class CurlOutputStream : GLib.OutputStream {
                                           ^
[100%] Linking C shared library libcurl-vala.so
[100%] Built target curl-vala
LThinkpad │ $ sudo make install                                                                                                                                                                                                                                                      │ 1023
[sudo] password for Luka: 
[100%] Built target curl-vala
Install the project...
-- Install configuration: ""
-- Installing: /usr/local/lib/libcurl-vala.so
-- Installing: /usr/local/share/vala/vapi/curl-vala.deps
-- Installing: /usr/local/share/vala/vapi/curl-vala.vapi
-- Installing: /usr/local/include/curl-vala.h
-- Installing: /usr/local/lib/pkgconfig/curl-vala.pc
LThinkpad │ $ cd ../examples                                                                                                                                                                                                                                                         │ 1024
LThinkpad │ $ make                                                                                                                                                                                                                                                                   │ 1025
valac fetch-website.vala --pkg curl-vala
/tmp/ccDNRNZi.o: In function `_vala_main':
fetch-website.vala.c:(.text+0xfb): undefined reference to `vcurl_easy_new'
fetch-website.vala.c:(.text+0x164): undefined reference to `vcurl_easy_set_url'
fetch-website.vala.c:(.text+0x191): undefined reference to `vcurl_easy_set_followlocation'
fetch-website.vala.c:(.text+0x1af): undefined reference to `vcurl_easy_perform'
fetch-website.vala.c:(.text+0x1d4): undefined reference to `vcurl_curl_error_quark'
collect2: error: ld returned 1 exit status
error: cc exited with status 256
Compilation failed: 1 error(s), 0 warning(s)
make: *** [Makefile:4: fetch-website] Error 1
LThinkpad │ $ 
```

**Comment by richard-w** [comment]
Seems like an impossible error. `vcurl_*` symbols are the GObject wrapper symbols which should be in libcurl-vala.so.

Follow the steps below. If any of them fails post the output here.

* Check the output of `readelf -W --dyn-syms /usr/local/lib/libcurl-vala.so`. `vcurl_easy_new` should show up there somewhere.
* Check the output of `pkg-config --cflags --libs curl-vala`. It should be `-I/usr/local/include -L/usr/local/lib -lcurl-vala`
* Check your `$CFLAGS` environment variable for funny stuff
* Execute `find / -name "libcurl-vala*"`. Only the entry in your builddir and the one in /usr/local/lib should show up.
* Try rebuilding curl-vala with `./configure --prefix=/usr` and see if it works then. After that you should remove it manually since the /usr prefix should only contain stuff installed by your package manager.

**Comment by richard-w** [comment]
I should point out that I didn't really deal with this project since 2013. Entirely possible there's something wrong here. It works fine on Ubuntu 16.04 as far as i can tell.

**Comment by LukaJankovic** [comment]
I followed your steps:
* It does show up
* Not matching. this is what I'm getting:
```Package curl-vala was not found in the pkg-config search path.         
Perhaps you should add the directory containing `curl-vala.pc'         
to the PKG_CONFIG_PATH environment variable                            
Package 'curl-vala', required by 'virtual:world', not found
```
* CFLAGS env variable is empty
* Seems to be in order (?):
```
LThinkpad │ $ sudo find / -name "libcurl-vala*"
/usr/local/lib/libcurl-vala.so
/home/Luka/Temp/curl-vala/build/libcurl-vala.so
find: ‘/run/user/1000/gvfs’: Permission denied
LThinkpad │ $  
```
* Running with `--prefix=/usr` gave me the same results as running configure normailly.

> I should point out that I didn't really deal with this project since 2013

I noticed that, which is why I was worried I wouldn't get any help whatsoever. So I'm really thankful that you're willing to help :) Currently running Fedora 27, Linux 4.14.14-300

**Comment by LukaJankovic** [comment]
I've tried to get [this example](https://github.com/Richard-W/curl-vala) and I'm getting similar errors (undefined reference). So it seems that it's not an issue directly related to this lib, but rather some combination of my setup, cmake and maybe something else.

**Comment by richard-w** [comment]
Yep. pkg-config Looks for the pc file in the wrong place.

Try
```
cd example
PKG_CONFIG_PATH=/usr/local/lib/pkgconfig make
```

**Comment by LukaJankovic** [comment]
Nope. Same error. Tried exporting PKG_CONFIG_PATH separately, but that didn't work either.

**Comment by richard-w** [comment]
As long as `pkg-config --cflags --libs curl-vala` will not output the expected libraries it won't work. You can work around it using the `-X` flag of vala to manually define libraries and include paths. Try adding `-X -I/usr/local/include -X -L/usr/local/lib -X -lcurl-vala` to your `valac` call.

**Comment by LukaJankovic** [comment]
Ok so I've decided to switch to Arch now... and things are going a bit smoother. running `PKG_CONFIG_PATH=/usr/local/lib/pkgconfig make` and then `LD_LIBRARY_PATH=/usr/local/lib ./fetch-website www.google.de` seems to work now at least!
